export default Object.freeze({
  WELCOME: 'Welcome',
  SIGNIN: 'SignIn',
  KEYVERIFY: 'KeyVerify',
  SIGNUP: 'SignUp',
  FORGOTPASSWORD: 'Forgot Password',
  HOME: 'Home',
  HOMEDEFAULT: 'HomeStack',
  PROFILEHOME: 'Profile Home',
  PERSONALINFO: 'Personal Info',
  VEHICLEINFO: 'Vehicle Info',
  PASSWORDCHANGE: 'Password Change',
  DELETEACCOUNT: 'Account Delete',
  SETTINGS: 'Settings',
  TRIPHISTORYHOME: 'Trip History Home',
  SETTINGHOME: 'Setting Home',
  PAYMENTHOME: 'PaymentHome',
  UBIAPP: 'UBI App',
  PAYMENTHISTORY: 'Payment History',
  TRIPHISTORY: 'Trip History',
  POLICYDETAILS: 'Policy Details',
  MESSAGES: 'Messages',
  NOTIFICATIONS: 'Notification',
  HELP: 'Help',
  PRIVACYPOLICY: 'Privacy Policy',
  DRAWERNAVIGATOR: 'Drawer Navigator'
});
