export default Object.freeze({
  WELCOME: 'Welcome',
  SIGNIN: 'SignIn',
  KEYVERIFY: 'KeyVerify',
  SIGNUP: 'SignUp',
  FORGOTPASSWORD: 'ForgotPassword',
  HOME: 'Home',
  HOMEDEFAULT: 'HomeStack',
  PROFILEHOME: 'ProfileHome',
  PERSONALINFO: 'PersonalInfo',
  VEHICLEINFO: 'VehicleInfo',
  PASSWORDCHANGE: 'PasswordChange',
  DELETEACCOUNT: 'AccountDelete',
  SETTINGS: 'Settings',
  TRIPHISTORYHOME: 'TripHistoryHome',
  SETTINGHOME: 'SettingHome',
  PAYMENTHOME: 'PaymentHome',
  UBIAPP: 'UBI App',
  PAYMENTHISTORY: 'PaymentHistory',
  TRIPHISTORY: 'TripHistory',
  POLICYDETAILS: 'PolicyDetails',
  MESSAGES: 'Messages',
  NOTIFICATIONS: 'Notification',
  HELP: 'Help',
  PRIVACYPOLICY: 'PrivacyPolicy',
});
